### ISSUE TITLE
Looping exception in console

### ISSUE THREAD

**Issue by iperrealistico** [Drawethree/PRO-DeathChest#15]
[15:16:43 WARN]: [DeathChestPro] Task #345 for DeathChestPro v3.4.8 generated an exception
java.lang.NullPointerException: null
        at sk.drawethree.deathchestpro.managers.DeathChestManager.removeDeathChest(DeathChestManager.java:153) ~[?:?]
        at sk.drawethree.deathchestpro.chest.DeathChest.removeDeathChest(DeathChest.java:277) ~[?:?]
        at sk.drawethree.deathchestpro.chest.tasks.ChestRemoveTask.run(ChestRemoveTask.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[15:16:44 WARN]: [DeathChestPro] Task #345 for DeathChestPro v3.4.8 generated an exception
java.lang.NullPointerException: null
        at sk.drawethree.deathchestpro.managers.DeathChestManager.removeDeathChest(DeathChestManager.java:153) ~[?:?]
        at sk.drawethree.deathchestpro.chest.DeathChest.removeDeathChest(DeathChest.java:277) ~[?:?]
        at sk.drawethree.deathchestpro.chest.tasks.ChestRemoveTask.run(ChestRemoveTask.java:22) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1292) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-133]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
        at java.lang.Thread.run(Thread.java:834) [?:?]

Paper version git-Paper-133
DeathChestPro version 3.4.8

**Comment by Drawethree** [comment]
Should be fixed in 3.4.9. Re-open the issue if still appears.
